---
title: "20150930Tutorial"
output: html_document
---


```{r}
getwd()
setwd("D:/OS DATA/Desktop")

match = read.table("match.txt", sep='|')
mat = matrix(-1, nrow=5, ncol=5)
colnames(mat) = c("A","B", "C","D", "E")
rownames(mat) = c("A","B", "C","D", "E")
mat["A","B"] = 1

for (i in 1:nrow(match)){
  row = match[i,];
  mat[row$V1, row$V2] = row$V3;
}

match_func = function(filename="match.txt"){
  match = read.table(filename, sep='|');
  mat = matrix(-1, nrow=5, ncol=5);
  colnames(mat) = c("A","B", "C","D", "E");
  rownames(mat) = c("A","B", "C","D", "E");
  for (i in 1:nrow(match)){
    row = match[i,];
    mat[row$V1, row$V2] = row$V3;
  }
  mat;
}



```



```{r}

getwd()
load('cdc.Rdata')
head(cdc)
class(cdc)
str(cdc)
names(cdc)
a = c(1,4,2,5,7,8,9)
hist(a)
hist(a, breaks = 2)
hist(a, freq=FALSE)
hist(cdc$weight)
hist(cdc$weight, breaks=50)
hist(cdc$weight, breaks=200)
table(cdc$weight %% 10)

stem(a)
b = c(172,173,178,182,183,189)
stem(b)

```


```{r}
a = c(25,23,32,52,65,38,42,57)
mean(a)

b = c(a, 300) 
mean(b)

a = sort(a)
median(a)

b = sort(b)
median(b)


mean(cdc$weight)
c = c(b, NA)
mean(b)
mean(c)
mean(c, na.rm=TRUE)

mean(cdc$weight)
median(cdc$weight)

set.seed(123)
sample.int(42,6)

set.seed(123)
temp = sample.int(30 , 100, replace=TRUE )

temp = c(temp, 999,999,999)
mean(temp)
median(temp)


a = c(1,4,4,4,1,2,2,1,4)
names(which.max(table(a)))

which.max(table(cdc$weight %% 10))

table(cdc$smoke100)
table(cdc$smoke100) / length(cdc$smoke100) 

barplot(table(cdc$smoke100))
barplot(table(cdc$smoke100), names.arg=c("nan", "smoke")) 

gender_smokers = table(cdc$gender, cdc$smoke100)

mosaicplot(gender_smokers)



```

```{r}
median(b)
quantile(b, 0.25)
quantile(b, 0.75)
quantile(b, 0.75) - quantile(b, 0.25)
IQR(b)

h1 = rnorm(1000, sd=1) 
h2 = rnorm(1000, sd=5) 


hist(h2, col="red")
hist(h1, col="blue", add=TRUE)
IQR(h2)
IQR(h1)

a = c(150, 155, 160, 162, 168, 171, 173, 175, 178, 182, 185)

stem(a)
quantile(a,0.75)
quantile(a,0.25)
IQR(a)


hist(cdc$weight)
boxplot(cdc$weight)

median(cdc$weight)
IQR(cdc$weight)

median(cdc$weight) + 1.5 * IQR(cdc$weight)

median(cdc$weight) - 1.5 * IQR(cdc$weight)


 boxplot(b[b< 300])
 
hist(cdc$height)
boxplot(cdc$height)

boxplot(cdc$height ~ cdc$gender)


bmi = (cdc$weight/cdc$height^2) * 703
boxplot(bmi ~ cdc$genhlth)

plot(cdc$weight, cdc$wtdesire)
```