---
title: "20151001Tutorial"
author: "David Chiu"
date: "2015年10月1日"
output: html_document
---

```{r}
data(mtcars)
names(mtcars)
mtcars[,1:3]
cov(mtcars[,1:3])
cor(mtcars[,1:3])

```
```{r}
binom.test(x=92, n=315, p=1/6)

boxplot(mtcars$mpg, mtcars$mpg[mtcars$am==0], ylab = "mpg", names=c("overall","automobile"))
abline(h=mean(mtcars$mpg),lwd=2, col="red")
abline(h=mean(mtcars$mpg[mtcars$am==0]),lwd=2, col="blue")



mpg.mu = mean(mtcars$mpg)
mpg_am = mtcars$mpg[mtcars$am == 0]
t.test(mpg_am,mu = mpg.mu)

boxplot(mtcars$mpg~mtcars$am,ylab='mpg',names=c('automatic','manual'))
abline(h=mean(mtcars$mpg[mtcars$am==0]),lwd=2, col="blue")
abline(h=mean(mtcars$mpg[mtcars$am==1]),lwd=2, col="red")
t.test(mtcars$mpg~mtcars$am)

```

```{r}
data(iris)
str(iris)
# install.packages("rpart")
library("rpart")

fit  = rpart(Species ~ Sepal.Length + Sepal.Width + Petal.Width + Petal.Length, data=iris)
fit
plot(fit, margin = 0.1)

plot(iris$Petal.Width, iris$Petal.Length)

plot(iris$Petal.Width, iris$Petal.Length, col=iris$Species)

abline(v = 0.8, col="red")
abline(v = 1.75, col="blue")


fit2  = rpart(Species ~ ., data=iris)

plot(fit2, margin = 0.1)
text(fit2)

plot(iris$Petal.Width, iris$Petal.Length, col=iris$Species)

abline(h = 2.45, col="red")
abline(v = 1.75, col="blue")

```


```{r}

install.packages("C50")
library("C50")
data(churn)
str(churnTrain)
churnTrain = churnTrain[,! names(churnTrain) %in% c("state", "area_code", "account_length") ]
nrow(churnTrain)

a = sample(c(0,1), 50, replace=TRUE, prob=c(0.8,0.2))
b = 1:50
b[a==0]
b[a==1]
set.seed(2)
ind <- sample(2, nrow(churnTrain), replace = TRUE, prob=c(0.7, 0.3))
trainset = churnTrain[ind == 1,]
testset = churnTrain[ind == 2,]
library(rpart)
 fit = rpart(churn ~., data=trainset)
plot(fit, margin = 0.1)
text(fit)


install.packages("party")
library(party)
 fit2 = ctree(churn ~., data=trainset)
 plot(fit2)
 
 
 fit3 = ctree(Species ~., data=iris)
 plot(fit3)
 
 churn.rp <- rpart(churn ~ ., data=trainset)
plot(churn.rp, margin= 0.1)
text(churn.rp, all=TRUE, use.n = TRUE)


min(churn.rp$cptable[,"xerror"])
which.min(churn.rp$cptable[,"xerror"])
churn.cp = churn.rp$cptable[7,"CP"]
prune.tree = prune(churn.rp, cp= churn.cp)
plot(prune.tree, margin= 0.1)
text(prune.tree, all=TRUE , use.n=TRUE)



churn.cp = churn.rp$cptable[5,"CP"]
prune.tree = prune(churn.rp, cp= churn.cp)
plot(prune.tree, margin= 0.1)
text(prune.tree, all=TRUE , use.n=TRUE)

head(predict(churn.rp, testset))
head(predict(churn.rp, testset, type="class"))
predictions = predict(churn.rp, testset, type="class")


data(iris)
fit = rpart(Species ~., data=iris)
pre2 = predict(fit, iris, type="class")
table(iris$Species, pre2)

install.packages("e1071")
library(e1071)
install.packages("caret")
library(caret)
control = trainControl(method="repeatedcv", number=10, repeats=3)
model = train(churn~., data=trainset, method="rpart", preProcess="scale", trControl=control)
model


install.packages("rminer")
library(rminer)
model=fit(churn~.,trainset,model="rpart")
VariableImportance=Importance(model,trainset,method="sensv")
L=list(runs=1,sen=t(VariableImportance$imp),sresponses=VariableImportance$sresponses)
mgraph(L,graph="IMP",leg=names(trainset),col="gray",Grid=10)


model=fit(churn~.,trainset,model="svm")
VariableImportance=Importance(model,trainset,method="sensv")
L=list(runs=1,sen=t(VariableImportance$imp),sresponses=VariableImportance$sresponses)
mgraph(L,graph="IMP",leg=names(trainset),col="gray",Grid=10)

```

```{r}
names(churnTrain) %in% c("churn", "total_intl_calls", "total_intl_charge")

new_train = trainset[,! names(churnTrain) %in% c("churn", "international_plan", "voice_mail_plan")]

cor_mat = cor(new_train)
highlyCorrelated = findCorrelation(cor_mat, cutoff=0.75)
names(new_train)[highlyCorrelated]

table(predictions, testset$churn)
library(caret)
confusionMatrix(table(predictions, testset$churn))
```

```{r}
install.packages("ROCR")
library(ROCR)

predictions <- predict(churn.rp, testset, type="prob")
pred.to.roc <- predictions[, 1] 
pred.rocr <- prediction(pred.to.roc, as.factor(testset[,(dim(testset)[[2]])])) 

perf.rocr <- performance(pred.rocr, measure = "auc", x.measure = "cutoff") 
perf.tpr.rocr <- performance(pred.rocr, "tpr","fpr") 
plot(perf.tpr.rocr, colorize=T,main=paste("AUC:",(perf.rocr@y.values)))


```