---
title: "Course1"
author: "David Chiu"
date: "Friday, May 15, 2015"
output: html_document
---

```{r}
#這是註解
3 + 3
#demo(graphics)
```

```{r, echo=FALSE}
# 數字相加
3 + 8
# 數字相減
3 - 8
# 數字相乘
5 * 5
# 數字相除
11 / 2
# 指數
2^10
# 取餘數
11%%2
```

```{r}
# 指定變數
a = 3
a

# 變數相加
b = 5
c = a + b
c
```

```{r}
# 數值型態
numer = 17.8
# 字串型態
char = "hello world"
# 布林邏輯
logic = TRUE

# 使用class 檢查資料型態
class(logic)


card_length = 3
card_width = "5 inches"
#card_length * card_width


#重新將card_width 指到5
card_width = 5
card_length * card_width
```
```{r}

height_vec = c(180,169,173)
name_vec = c("Brian", "Toby", "Sherry")
# 兩個向量進行數學運算
x = c(1,2,3,7) 
y= c(2,3,5,1)

x+y 
x*y
x-y 
x/y

x = c(1,2,3,7) 
sum(x)

height_vec = c(180,169,173)
height_vec

names(height_vec) = c("Brian", "Toby", "Sherry")
height_vec

name_vec = c("Brian", "Toby", "Sherry")
names(height_vec) = name_vec


```

```{r}
height_vec = c(180,169,173)
weight_vec = c(73,87,43)
name_vec = c("Brian", "Toby", "Sherry")
bmi_vec = weight_vec / (height_vec/100) ^2
names(bmi_vec) = c("Brian", "Toby", "Sherry")
bmi_vec[bmi_vec < 18.5 | bmi_vec >=24]
```

```{r}
a = c(1,2,3,4,5)
a = 1:5
a = 1:100
sum(1:100)
```

```{r}
matrix(2:4, nrow=3)
matrix(2:4, nrow=1)

matrix(1:9, byrow=TRUE, nrow=3)
matrix(1:9, nrow=3)

cbind(height_vec, weight_vec)
rbind(height_vec, weight_vec)

kevin = c(85,73)
marry = c(72,64)
jerry = c(59,66)

mat = matrix(c(kevin, marry, jerry), nrow=3, byrow= TRUE)
class(mat)
colnames(mat) = c('first', 'second')
rownames(mat) = c('kevin', 'marry', 'jerry')

mat2 = matrix(c(kevin, marry, jerry), nrow=3, byrow=TRUE, 
dimnames=list(c('kevin', 'marry', 'jerry'),c('first', 'second')))

#取維度
dim(mat2)

#取列數
nrow(mat2)

#取行數
ncol(mat2)

#slicing
height_vec[c(2,3)]
height_vec[2:3]

#取第一列
mat2[1,] 

#取第一行
mat2[,1]

#取第二、三列
mat2[2:3,]
mat2[c(2,3),]

#取第一、三列
mat2[c(1,3),]

#取第二列第一行的元素
mat2[2,1]

#取得第二個與第三個元素 (由第一列第一行到最後一列最後一行, 由上往下掃) 
mat[2:3]

#新增學生資料
mat3 = rbind(mat2, c(78,63))
rownames(mat3)
rownames(mat3)[4] = "sam"
rownames(mat3)
nrow(mat3)

rownames(mat3)[nrow(mat3)] = 'sam'
#  rownames(mat3)[4] = "sam"
mat3

#新增考試分數
mat4 = cbind(mat2,c(82,77,70))
colnames(mat4)
colnames(mat4)[3]
colnames(mat4)[ncol(mat4)]
colnames(mat4)[ncol(mat4)] = 'third'
mat4

rowSums(mat2)
# sum(mat4[1,])
colSums(mat2)

#矩陣宣告
m1 = matrix(1:4, byrow=TRUE, nrow=2)
m2 = matrix(5:8, byrow=TRUE, nrow=2)

#矩陣運算
m1 + m2
m1 - m2
m1 * m2
m1 / m2

# what if 1/0
 1 / 0 

#m1 X m2 
m1 %*% m2

mat[,1] * 0.4 + mat[,2] *0.6
mat

mat %*% c(0.4, 0.6)

matrix(1:9, nrow=9) %*% matrix(1:9, nrow=1)
```
```{r}
weather= c("sunny","rainy", "cloudy", "rainy", "cloudy")
class(weather)
weather_category = factor(weather)
weather_category

#假使我們沒有跟他說這是類別
a = c(1,1,1,0,0)
plot(a)
a = factor(c(1,1,1,0,0))
plot(a)
a
#[1] 1 1 1 0 0
# Levels: 0 1

unique(weather_category)

temperature = c("Low", "High", "High", "Medium", "Low", "Medium")
temperature_category = factor(temperature, order = TRUE, levels = c("Low", "Medium", "High"))
temperature_category
temperature_category[3] > temperature_category[1]
temperature_category[4] > temperature_category[3]
levels(weather_category)
levels(temperature_category)


a = c('car', 'car', 'river', 'bar', 'bar', 'qoo', 'car')
factor()
factor(a)
levels(factor(a))

weather= c("s","r", "c", "r", "c")
weather_factor = factor(weather)
levels(weather_factor) = c("cloudy","rainy","sunny")
weather_factor

```

```{r}
#表列資料集
data()
#使用資料集
data(iris)
#觀察讀取到的資料集型態
class(iris)
str(iris)
#自行建立Data Frame
df = data.frame(a=c(1,2,3,4,5),b=c(2,3,4,5,6))
class(df)

#觀看前幾筆資料
head(iris)
head(iris, 10)
#觀看後幾筆資料
tail(iris)
tail(iris, 10)
#使用str 函式檢視架構
str(iris)
#取前三列資料
iris[1:3,]
#取前三列第一行的資料
iris[1:3,1]
#也可以用欄位名稱取值
iris[1:3,"Sepal.Length"]
iris[1:3,c("Sepal.Length", "Petal.Length")]

#取前兩行資料
head(iris[,1:2])
#取特定欄位向量值
iris$"Sepal.Length"

#取前五筆包含length 及 width 的資料
Five.Sepal.iris = iris[1:5, c("Sepal.Length", "Sepal.Width")]

#可以用條件做篩選
setosa.data = iris[iris$Species=="setosa",1:5]
setosa.data2 = iris[which(iris$Species=="setosa"),1:5]
#使用which 做資料篩選
which(iris$Species=="setosa")

#以Merge 做資料合併
flower.type = data.frame(Species = "setosa", Flower = "iris")
merge(flower.type, iris[1:3,], by ="Species")

#用order做資料排序
iris[order(iris$Sepal.Length, decreasing = TRUE),]

a = c(2,1,5,3,6,7)
sort(a)
order(a)

#Pie Chart
table.iris = table(iris$Species)
pie(table.iris)
#Histogram
hist(iris$Sepal.Length)
#Box Plot
boxplot(Petal.Width ~ Species, data = iris)
#Scatter Plot
plot(x=iris$Petal.Length, y=iris$Petal.Width, col=iris$Species)
stock_data = read.csv("~/Desktop/2330.csv", head=TRUE)
stock_data$tf = ifelse(stock_data$Close - stock_data$Open > 0, TRUE, FALSE)
 table(stock_data$tf)
stock_data$rise_down_range = cut(stock_data$Close - stock_data$Open, breaks=quantile(stock_data$Close - stock_data$Open))
table(stock_data$rise_down_range)

stock_data$Date = as.Date(stock_data$Date)
str(stock_data)
stock_data[stock_data$Date >= '2015-03-01' & stock_data$Date < '2015-08-01'  ,]
stock_data[stock_data$Date >= '2015-03-01' & stock_data$Date < '2015-08-01'  ,"Close"]
max(stock_data[stock_data$Date >= '2015-03-01' & stock_data$Date < '2015-08-01'  ,"Close"])

stock_data2 = stock_data[stock_data$Date >= '2015-03-01' & stock_data$Date < '2015-08-01'  ,"Close"]
boxplot(stock_data2)
plot(stock_data$Date, stock_data$Close)

```
