---
title: "Course3"
author: "David Chiu"
date: "Thursday, May 21, 2015"
output: html_document
---

```{r}
rnorm(10)
hist(rnorm(10))

hist(rnorm(100))
hist(rnorm(1000))

curve(dnorm,-3,3)
abline(v = 1.5, col="red")
dnorm(0)
dnorm(0,mean=3,sd=5)
pnorm(1.5)


set.seed(50)
y = runif(1000,0,5)
hist(y)

hist(rpois(5000,3))
load("cdc.Rdata")
shapiro.test(sample(cdc$weight,5000))



```
```{r}
sample(1:10)
set.seed(50)
sample(1:42, size = 6)
sample(c(0,1), 10, replace = TRUE)
sample(c("tail","head"), 10, replace = TRUE)
sample.int(20, 12)
sample.int(42, 6)


coins = c("heads", "tails")
fair_coin = sample(coins, size = 1000, replace = TRUE)
table(fair_coin)

outcomes = c("heads", "tails")
unfair_coin = sample(outcomes, size = 100, replace = TRUE, prob = c(0.3,0.7))
table(unfair_coin)


```

```{r}

load("~/Desktop/kobe.RData")
get_streak = function(x){
  y = rep(0,length(x))
  y[x == "H"] = 1
  y = c(0, y, 0)
  wz = which(y == 0)
  streak = diff(wz) - 1
  return(streak)
}

outcomes = c("H", "M")
sim_basket = sample(outcomes, size = 133, replace = TRUE, prob = c(0.45, 0.55))

table(sim_basket)

kobe_streak = get_streak(kobe$basket)
sim_streak = get_streak(sim_basket)

summary(kobe_streak)
summary(sim_streak)

kobe_table = table(kobe_streak)
sim_table = table(sim_streak)

par(mfrow = c(1, 2))
barplot(kobe_table)
barplot(sim_table)
#barplot(cbind(kobe_table[1:4], sim_table[1:4]), plot = TRUE, beside = TRUE)

```

```{r}
load("~/Desktop/ames.Rdata")
class(ames)
head(ames)
tail(ames)

area = ames$Gr.Liv.Area
hist(area)
shapiro.test(area)
sample_means10 = rep(NA, 5000)
sample_means50 = rep(NA, 5000)
sample_means100 = rep(NA, 5000)

for (i in 1:5000) {
    samp = sample(area, 10)
    sample_means10[i] = mean(samp)
    samp = sample(area, 50)
    sample_means50[i] = mean(samp)
    samp = sample(area, 100)
    sample_means100[i] = mean(samp)
}

par(mfrow = c(3, 1))

xlimits = range(sample_means10)

hist(sample_means10, breaks = 20, xlim = xlimits)
hist(sample_means50, breaks = 20, xlim = xlimits)
hist(sample_means100, breaks = 20, xlim = xlimits)


population = ames$Gr.Liv.Area
samp = sample(population, 50)
sample_mean = mean(samp)
hist(samp)


#標準誤差
sde = sd(samp)/sqrt(50)

#隨機區間: 95%的信心 ，平均數會落在平均數加減1.96標準誤差的區間中
lower = sample_mean - 1.96 * sde
upper = sample_mean + 1.96 * sde

qnorm(0.975)
pnorm(1.96)

```
