---
title: "20150930Tutorial"
output: html_document
---


```{r}
getwd()
setwd("D:/OS DATA/Desktop")

match = read.table("match.txt", sep='|')
mat = matrix(-1, nrow=5, ncol=5)
colnames(mat) = c("A","B", "C","D", "E")
rownames(mat) = c("A","B", "C","D", "E")
mat["A","B"] = 1

for (i in 1:nrow(match)){
  row = match[i,];
  mat[row$V1, row$V2] = row$V3;
}

match_func = function(filename="match.txt"){
  match = read.table(filename, sep='|');
  mat = matrix(-1, nrow=5, ncol=5);
  colnames(mat) = c("A","B", "C","D", "E");
  rownames(mat) = c("A","B", "C","D", "E");
  for (i in 1:nrow(match)){
    row = match[i,];
    mat[row$V1, row$V2] = row$V3;
  }
  mat;
}



```



```{r}

getwd()
load('cdc.Rdata')
head(cdc)
class(cdc)
str(cdc)
names(cdc)
a = c(1,4,2,5,7,8,9)
hist(a)
hist(a, breaks = 2)
hist(a, freq=FALSE)
hist(cdc$weight)
hist(cdc$weight, breaks=50)
hist(cdc$weight, breaks=200)
table(cdc$weight %% 10)

stem(a)
b = c(172,173,178,182,183,189)
stem(b)

```


```{r}
a = c(25,23,32,52,65,38,42,57)
mean(a)

b = c(a, 300) 
mean(b)

a = sort(a)
median(a)

b = sort(b)
median(b)


mean(cdc$weight)
c = c(b, NA)
mean(b)
mean(c)
mean(c, na.rm=TRUE)

mean(cdc$weight)
median(cdc$weight)

set.seed(123)
sample.int(42,6)

set.seed(123)
temp = sample.int(30 , 100, replace=TRUE )

temp = c(temp, 999,999,999)
mean(temp)
median(temp)


a = c(1,4,4,4,1,2,2,1,4)
names(which.max(table(a)))

which.max(table(cdc$weight %% 10))

table(cdc$smoke100)
table(cdc$smoke100) / length(cdc$smoke100) 

barplot(table(cdc$smoke100))
barplot(table(cdc$smoke100), names.arg=c("nan", "smoke")) 

gender_smokers = table(cdc$gender, cdc$smoke100)

mosaicplot(gender_smokers)



```

```{r}
median(b)
quantile(b, 0.25)
quantile(b, 0.75)
quantile(b, 0.75) - quantile(b, 0.25)
IQR(b)

h1 = rnorm(1000, sd=1) 
h2 = rnorm(1000, sd=5) 


hist(h2, col="red")
hist(h1, col="blue", add=TRUE)
IQR(h2)
IQR(h1)

a = c(150, 155, 160, 162, 168, 171, 173, 175, 178, 182, 185)

stem(a)
quantile(a,0.75)
quantile(a,0.25)
IQR(a)


hist(cdc$weight)
boxplot(cdc$weight)

median(cdc$weight)
IQR(cdc$weight)

median(cdc$weight) + 1.5 * IQR(cdc$weight)

median(cdc$weight) - 1.5 * IQR(cdc$weight)


 boxplot(b[b< 300])
 
hist(cdc$height)
boxplot(cdc$height)

boxplot(cdc$height ~ cdc$gender)


bmi = (cdc$weight/cdc$height^2) * 703
boxplot(bmi ~ cdc$genhlth)

plot(cdc$weight, cdc$wtdesire)
```


```{r}
 hist(rnorm(100))

hist(rnorm(1000))
hist(rnorm(1000), freq=FALSE)

curve(dnorm, -3,3)
dnorm(0)
pnorm(1)
abline(v=-1, col="blue")
pnorm(-1)
pnorm(1) - pnorm(-1)


 curve(dnorm, -20,20, col ="red")
curve(dnorm(x, mean=3, sd= 5), -12, 16, add=TRUE, col="blue")
curve(dnorm(x, mean=3, sd= 5), -12, 16)

abline(v = 0, col="red")
abline(h = 0.06664492, col="blue")
dnorm(0, mean=3, sd= 5)

curve(pnorm(x), -3,3)
abline(v=1, col="red")

set.seed(50)
y = runif(1000,0,5)
hist(y)

x = rnorm(1000)
hist(x)


set.seed(50)
y = runif(1000,0,5)
hist(y)
x = rnorm(1000)
hist(x)
y = runif(1000,0,5)
hist(y)

hist(rpois(5000,3))

shapiro.test(cdc$weight)
shapiro.test(rnorm(1000))
```

```{r}
sample(1:10)
sample(1:10, size = 5)
sample(c(0,1), 10, replace = TRUE)
sample.int(20, 12)

coins = c("heads", "tails")
fair_coin = sample(coins, size = 100, replace = TRUE)
table(fair_coin)
fair_coin

outcomes = c("heads", "tails")


unfair_coin = sample(outcomes, size = 100, replace = TRUE, prob = c(0.3,0.7))
table(unfair_coin)

```


```{r}
load("ames.Rdata")

area = ames$Gr.Liv.Area
hist(area)
shapiro.test(area)


sample_means10 = rep(NA, 5000)
sample_means50 = rep(NA, 5000)
sample_means100 = rep(NA, 5000)


for (i in 1:5000) {
    samp = sample(area, 10)
    sample_means10[i] = mean(samp)
    samp = sample(area, 50)
    sample_means50[i] = mean(samp)
    samp = sample(area, 100)
    sample_means100[i] = mean(samp)
}

par(mfrow = c(3, 1))

xlimits = range(sample_means10)

hist(sample_means10, breaks = 20, xlim = xlimits)
hist(sample_means50, breaks = 20, xlim = xlimits)
hist(sample_means100, breaks = 20, xlim = xlimits)

```

```{r}
population = ames$Gr.Liv.Area
samp = sample(population, 50)
sample_mean = mean(samp)

pnorm(1.96) - pnorm(-1.96)
 curve(dnorm, -3,3)
x = c(-1.96, seq(-1.96, 1.96, 0.01), 1.96)
y = c(0, dnorm(seq(-1.96, 1.96, 0.01)), 0)
polygon(x = x, y = y, add=TRUE, col="blue")

sde = sd(samp)/sqrt(50)
lower  = sample_mean - 1.96 * sde
upper  = sample_mean + 1.96 * sde

```