---
title: "Course3"
author: "David Chiu"
date: "Thursday, May 21, 2015"
output: html_document
---
```{r}
a = 3 #numeric
a = c(1,2,3,4,5) # vector
a = matrix(1:4, byrow=TRUE, nrow = 2) # matrix
a = data.frame(a =c(1,2), b=c(3,4)) # data frame
a = list(a =c(1,2,3), b = "hello world") # list
a = factor(c(1,2,3,3,3,2,1)) # factor
```

```{r}
summary(cdc)
str(cdc)
hist(cdc$weight)
boxplot(cdc$weight)
boxplot(cdc$weight[cdc$weight< 450])
```


```{r}
a = c(1,2,3,4,5)
#absolute distance
sum(abs(a - 3))

#variance
sum(((a - mean(a)) ^ 2)) /4
var(a) 

sd(a) #sqrt(var(a))
```
 
```{r}
rnorm(10)
hist(rnorm(10))

hist(rnorm(100))
hist(rnorm(1000))

curve(dnorm,-3,3)
abline(v = 1.5, col="red")
dnorm(0)
dnorm(0,mean=3,sd=5)
pnorm(1.5)


set.seed(50)
y = runif(1000,0,5)
hist(y)

hist(rpois(5000,3))
load("cdc.Rdata")
shapiro.test(sample(cdc$weight,5000))

set.seed(2)
head(.Random.seed,10)

a = rnorm(10000, mean= 30000, sd = 5000)
hist(a)
sample.a = sample(a, 1000)
mean(sample.a)
shapiro.test(sample.a)

low.salary = rnorm(10000, mean= 22000, sd = 3000)
high.salary = rnorm(10000, mean= 220000, sd = 30000)
hist(c(low.salary, high.salary))
mean(c(low.salary, high.salary))
# 121032.7

sample.population = sample(c(low.salary, high.salary), 1000)
mean(sample.population)

```
```{r}
sample(1:10)
set.seed(50)
sample(1:42, size = 6)
sample(c(0,1), 10, replace = TRUE)
sample(c("tail","head"), 10, replace = TRUE)
sample.int(20, 12)
sample.int(42, 6)


coins = c("heads", "tails")
fair_coin = sample(coins, size = 1000, replace = TRUE)
table(fair_coin)

outcomes = c("heads", "tails")
unfair_coin = sample(outcomes, size = 100, replace = TRUE, prob = c(0.3,0.7))
table(unfair_coin)


```

```{r}

load("~/Desktop/kobe.RData")
get_streak = function(x){
  y = rep(0,length(x))
  y[x == "H"] = 1
  y = c(0, y, 0)
  wz = which(y == 0)
  streak = diff(wz) - 1
  return(streak)
}

outcomes = c("H", "M")
sim_basket = sample(outcomes, size = 133, replace = TRUE, prob = c(0.45, 0.55))

table(sim_basket)

kobe_streak = get_streak(kobe$basket)
sim_streak = get_streak(sim_basket)

summary(kobe_streak)
summary(sim_streak)

kobe_table = table(kobe_streak)
sim_table = table(sim_streak)

par(mfrow = c(1, 2))
barplot(kobe_table)
barplot(sim_table)
#barplot(cbind(kobe_table[1:4], sim_table[1:4]), plot = TRUE, beside = TRUE)

```

```{r}
load("~/Desktop/ames.Rdata")
class(ames)
head(ames)
tail(ames)

area = ames$Gr.Liv.Area
hist(area)
shapiro.test(area)
sample_means10 = rep(NA, 5000)
sample_means50 = rep(NA, 5000)
sample_means100 = rep(NA, 5000)

for (i in 1:5000) {
    samp = sample(area, 10)
    sample_means10[i] = mean(samp)
    samp = sample(area, 50)
    sample_means50[i] = mean(samp)
    samp = sample(area, 100)
    sample_means100[i] = mean(samp)
}

par(mfrow = c(3, 1))

xlimits = range(sample_means10)

hist(sample_means10, breaks = 20, xlim = xlimits)
hist(sample_means50, breaks = 20, xlim = xlimits)
hist(sample_means100, breaks = 20, xlim = xlimits)


population = ames$Gr.Liv.Area
samp = sample(population, 50)
sample_mean = mean(samp)
hist(samp)


#標準誤差
sde = sd(samp)/sqrt(50)

#隨機區間: 95%的信心 ，平均數會落在平均數加減1.96標準誤差的區間中
lower = sample_mean - 1.96 * sde
upper = sample_mean + 1.96 * sde

qnorm(0.975)
pnorm(1.96)

```

```{r}
data(mtcars)
cov(mtcars[,1:3])
cor(mtcars[,1:3])
qplot(x=Var1, y=Var2, data=melt(cor(mtcars[1:3])), fill=value, geom="tile")
qplot(x=Var1, y=Var2, data=melt(cor(mtcars[1:3])), fill=value, geom="tile") + scale_fill_gradient(low = "pink", high = "green")
```

```{r}
load("mlb11.Rdata")
plot(mlb11$runs ~ mlb11$at_bats)
m1 = lm(runs ~ at_bats, data = mlb11)
abline(m1)
predict(m1, data.frame(at_bats = 5700))

```

```{r}
binom.test(x=92, n=315, p=1/6)

boxplot(mtcars$mpg, mtcars$mpg[mtcars$am==0], ylab = "mpg", names=c("overall","automobile"))
abline(h=mean(mtcars$mpg),lwd=2, col="red")
abline(h=mean(mtcars$mpg[mtcars$am==0]),lwd=2, col="blue")

mpg.mu = mean(mtcars$mpg)
mpg_am = mtcars$mpg[mtcars$am == 0]
t.test(mpg_am,mu = mpg.mu)

boxplot(mtcars$mpg~mtcars$am,ylab='mpg',names=c('automatic','manual'))
abline(h=mean(mtcars$mpg[mtcars$am==0]),lwd=2, col="blue")
abline(h=mean(mtcars$mpg[mtcars$am==1]),lwd=2, col="red")

t.test(mtcars$mpg~mtcars$am)

#產生類別資料統計
ftable = table(mtcars$am, mtcars$gear)
#繪製類別資料
mosaicplot(ftable, main="Number of Forward Gears Within Automatic and Manual Cars", color = TRUE)

chisq.test(ftable)

boxplot(mtcars$mpg~factor(mtcars$gear),xlab='gear',ylab='mpg')
 oneway.test(mtcars$mpg~factor(mtcars$gear))

 mtcars.aov <- aov(mtcars$mpg ~ as.factor(mtcars$gear))
 summary(mtcars.aov)

par(mfrow=c(1,2))
boxplot(mtcars$mpg~mtcars$gear,subset=(mtcars$am==0),xlab='gear', ylab = "mpg",main= 'manual’ )
boxplot(mtcars$mpg~mtcars$gear,subset=(mtcars$am==1),xlab='gear', ylab = "mpg", main='automatic’)

boxplot(mtcars$mpg~factor(mtcars$gear)* factor(mtcars$am),xlab='gear * transmission', ylab = "mpg",main='Boxplot of mpg by gear * transmission')

mpg_anova2 = aov(mtcars$mpg~factor(mtcars$gear)*factor(mtcars$am))
summary(mpg_anova2) 

```
